runtime: nodejs20
handlers:
- url: /.*
  secure: always
  script: auto
  http_headers:
    Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; connect-src 'self'; form-action 'none';"
automatic_scaling:
  min_instances: 3
  max_pending_latency: 500ms
