version: 2.1

executors:
  node:
    docker:
      - image: node:12
        user: node
  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

commands:
  deploy-env:
    description: "Deploy to a specific environment"
    parameters:
      sa_key_var:
        type: string
        default: "SA_KEY_JSON"
      env:
        type: string
        default: "dev"
      pr:
        type: boolean
        default: false
    steps:
      - checkout
      - run: mkdir tmp ; touch tmp/foo
      - attach_workspace:
          at: tmp
      - run: mv tmp/* .
      - run: rmdir tmp
      - run: cp config/<< parameters.env >>.json config.json
      - run: echo "$<< parameters.sa_key_var >>" > /tmp/sa.json
      - run: gcloud auth activate-service-account --key-file=/tmp/sa.json
      - run: gcloud app deploy --project=terra-bard-<< parameters.env >> --promote --quiet

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: $CACHE_VERSION-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: $CACHE_VERSION-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run: yarn generate-docs
      - persist_to_workspace:
          root: .
          paths:
            - docs
            - node_modules
  deploy-dev:
    executor: gcloud
    steps: 
      - deploy-env:
          sa_key_var: "DEV_SA_KEY_JSON"

workflows:
  version: 2
  build-deploy: 
    jobs: 
      - build
      - deploy-dev:
          requires:
            - build
