version: 2.1

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run: yarn lint
