// This and the test below makes sure the build will fail reasonably if you try
// to publish without the environment variables defined.

def garProjectId = System.getenv("GOOGLE_CLOUD_PROJECT")
def garLocation = System.getenv("GAR_LOCATION")
def garRepoId = System.getenv("GAR_REPOSITORY_ID")

gradle.taskGraph.whenReady { taskGraph ->
	if (taskGraph.hasTask(publish) &&
			(garProjectId == null || garLocation == null || garRepoId == null)) {
		throw new GradleException('Set env vars GOOGLE_CLOUD_PROJECT, GAR_LOCATION, and GAR_REPOSITORY_ID to publish')
	}
}

java {
	// Builds sources into the published package as part of the 'assemble' task.
	withSourcesJar()
}

publishing {
	publications {
		bardResttemplateClientLibrary(MavenPublication) {
			artifactId = 'bard-client-resttemplate'
			from components.java
			versionMapping {
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
		}
  }
  repositories {
    maven {
      url = uri("artifactregistry://${garLocation}-maven.pkg.dev/${garProjectId}/${garRepoId}")
    }
  }
}
